## Tensor Initialization

In [15]:
import torch
import numpy as np

In [16]:
## setting device 
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu


In [17]:
my_tensor = torch.tensor([[1,2,3,5,6],[2,3,4,5,6]], dtype = torch.float32, device=device, requires_grad=True)
## printing tensor
print(my_tensor)

## to know the shape
print(my_tensor.shape)

## to know the dtyoe of it 
print(my_tensor.dtype)

## to know if it require grad or not
print(my_tensor.requires_grad)


tensor([[1., 2., 3., 5., 6.],
        [2., 3., 4., 5., 6.]], requires_grad=True)
torch.Size([2, 5])
torch.float32
True


### Common initialization method

In [22]:

#1) Empty Method (uninitialize contains  Random Garbage)
x = torch.empty(size = (3,3))
print(x)

#2) Zeros Initialization (initilizae the matrix with zeros)
x = torch.zeros(size = (2,3))
print(x)

#3) rand initialization (initialize the matrix with uniform distribution [0,1)
x = torch.rand(size =(4,5))
print(x)

#4) Ones Initialization (initialize the matrix with one)
x = torch.ones(size = (3,4))
print(x)

#5)eye Identity Matrix Initialization (9nitialize the matrix ) or put one diagoally
x = torch.eye( 5,5)
print(x)


#6) arange -> like range in pyth 
x = torch.arange(start=0,end= 10, step=1) # same as torch.arange(10)
print(x)
x = torch.arange(start=3, end = 17, step = 4)
print(x)


## ******* Important linspace (pickup the numebr from equal space) ************
x = torch.linspace(start=0, end=1 , steps = 10) # picking up 10 numbers between 0 and 1 ,at equal spaces
print(x)


## Initialization with Normal Distribution 
x = torch.empty(size = (3,3)).normal_(mean=0, std=1)
print(x)

## Initiliazation with Uniform  Distribution
x = torch.empty(size = (3,3)).uniform_(0,1) ## same like torch.rand(size = (3,3))
print(x)



## *** diag -> input 1D -> create 2D matrix with that diag and input 2D, output 1D with diagonal value 
oneD_input = torch.tensor([1,3,4,3,4])
x = torch.diag(oneD_input)

twoD_input = torch.rand(size = (3,3))
print(twoD_input)
diagonal_elements = torch.diag(twoD_input)
print(diagonal_elements)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5847, 0.6413, 0.7360, 0.5584, 0.0850],
        [0.2277, 0.9081, 0.1060, 0.5442, 0.5525],
        [0.4843, 0.8439, 0.6012, 0.6967, 0.6459],
        [0.2704, 0.5306, 0.9053, 0.9470, 0.7340]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 3,  7, 11, 15])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([[-0.9589, -0.7269, -2.0044],
        [-0.7565,  1.0650, -0.5159],
        [ 0.7689,  0.4954,  0.3918]])
tensor([[0.3080, 0.6036, 0.1033],
        [0.7779, 0.2541, 0.6638],
        [0.6600, 0.2138, 0.6510]])
tensor([[0.4573, 0.9258, 0.5546],
        [0.4287, 0.0931, 0.3083],
        [0.39

### Changing Data type of Tensor

In [23]:
x = torch.tensor([1,0,0,4])
print(x.dtype)

## into boolean
print(x.bool().dtype)

## into short
print(x.short().dtype) # into int 16

## into long 
print(x.long().dtype) # into int 64

## into half
print(x.float().dtype) # covert into float 32 *********Impportant!! *******88

## into double
print(x.double().dtype) # convert to float 64


torch.int64
torch.bool
torch.int16
torch.int64
torch.float32
torch.float64


### numpy  array to  torch tensor , torch tensor to numpy numpy array

In [24]:
numpy_arr= np.array([1,3,4,5])
## .from_numpy()
tensor = torch.from_numpy(numpy_arr)
print(tensor)

## .numpy()
numpy_arr = tensor.numpy()

print(numpy_arr)
print(type(numpy_arr))

tensor([1, 3, 4, 5])
[1 3 4 5]
<class 'numpy.ndarray'>


## Tensor Math and Comparision 