## Tensor Initialization

In [1]:
import torch
import numpy as np

In [8]:
## setting device 
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu


In [3]:
my_tensor = torch.tensor([[1,2,3,5,6],[2,3,4,5,6]], dtype = torch.float32, device=device, requires_grad=True)
## printing tensor
print(my_tensor)

## to know the shape
print(my_tensor.shape)

## to know the dtyoe of it 
print(my_tensor.dtype)

## to know if it require grad or not
print(my_tensor.requires_grad)


tensor([[1., 2., 3., 5., 6.],
        [2., 3., 4., 5., 6.]], requires_grad=True)
torch.Size([2, 5])
torch.float32
True


### Common initialization method

In [ ]:

#1) Empty Method (uninitialize contains  Random Garbage)
x = torch.empty(size = (3,3))
print(x)

#2) Zeros Initialization (initilizae the matrix with zeros)
x = torch.zeros(size = (2,3))
print(x)

#3) rand initialization (initialize the matrix with uniform distribution [0,1)
x = torch.rand(size =(4,5))
print(x)

#4) Ones Initialization (initialize the matrix with one)
x = torch.one(size = (3,4))
print(x)

#5)eye Identity Matrix Initialization (9nitialize the matrix ) or put one diagoally
x = torch.eye(size = (5,5))
print(x)


#6) arange -> like range in pyth 
x = torch.arange(start=0,end= 10, step=1) # same as torch.arange(10)
print(x)
x = torch.arange(start=3, end = 17, step = 4)
print(x)


## ******* Important linspace (pickup the numebr from equal space) ************
x = torch.linspace(start=0, end=1 , step = 10) # picking up 10 numbers between 0 and 1 ,at equal spaces
print(x)


## Initialization with Normal Distribution 
x = torch.empty(size = (3,3)).normal_(mean=0, std=1)
print(x)

## Initiliazation with Uniform  Distribution
x = torch.empty(size = (3,3)).uniform_(0,1) ## same like torch.rand(size = (3,3))
print(x)



## *** diag -> input 1D -> create 2D matrix with that diag and input 2D, output 1D with diagonal value 
oneD_input = torch.tensor([1,3,4,3,4])
x = torch.diag(oneD_input)

twoD_input = torch.rand(size = (3,3))
print(twoD_input)
diagonal_elements = torch.diag(twoD_input)
print(diagonal_elements)


tensor([[6.6213e-24, 1.1028e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


### Changing Data type of Tensor

In [12]:
x = torch.tensor([1,0,0,4])
print(x.dtype)

## into boolean
print(x.bool().dtype)

## into short
print(x.short().dtype) # into int 16

## into long 
print(x.long().dtype) # into int 64

## into half
print(x.float().dtype) # covert into float 32 *********Impportant!! *******88

## into double
print(x.double().dtype) # convert to float 64


torch.int64
torch.bool
torch.int16
torch.int64
torch.float32
torch.float64


### numpy  array to  torch tensor , torch tensor to numpy numpy array

In [14]:
numpy_arr= np.array([1,3,4,5])
## .from_numpy()
tensor = torch.from_numpy(numpy_arr)
print(tensor)

## .numpy()
numpy_arr = tensor.numpy()

print(numpy_arr)
print(type(numpy_arr))

tensor([1, 3, 4, 5])
[1 3 4 5]
<class 'numpy.ndarray'>


## Tensor Math and Comparision 